_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 49
                - 55
                - 82
                - 83
            "2":
                - 1
                - 49
                - 55
                - 82
                - 83
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
architecture:
    value: 1D EEG Diffusion Model
batch_size:
    value: 32
dataset:
    value: EEG-DIF-1D
epochs:
    value: 200
learning_rate:
    value: 0.0001
noise_schedule:
    value: cosine
notes:
    value: Optimized parameters for EEG signal generation
prediction_point:
    value: 768
