_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 49
                - 55
                - 82
                - 83
            "2":
                - 1
                - 49
                - 55
                - 82
                - 83
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
architecture:
    value: EEG-Optimized 1D EEG Diffusion Model
batch_size:
    value: 16
dataset:
    value: EEG-DIF-1D
epochs:
    value: 15
learning_rate:
    value: 1e-05
model_size:
    value: small_smooth
notes:
    value: Fixed conditioning preservation bug, simplified training loss, better evaluation metrics
optimization_focus:
    value: conditioning_preservation_and_correlation
